//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGSW.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeoUrl
    {
        public int Id { get; set; }
        public Nullable<double> ZIPCode { get; set; }
        public string ZIPType { get; set; }
        public string CityName { get; set; }
        public string CityType { get; set; }
        public string CountyName { get; set; }
        public Nullable<double> CountyFIPS { get; set; }
        public string StateName { get; set; }
        public string StateAbbr { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SeoName { get; set; }
    }
}
