//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGSW.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survery
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.Guid> SurveryGuid { get; set; }
        public int Question1 { get; set; }
        public int Question2 { get; set; }
        public int Question3 { get; set; }
        public int Question4 { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    
        public virtual GutterCleanOrder GutterCleanOrder { get; set; }
    }
}
